staticSites:
  - name: metrooffice-website
    buildCommand: ""
    staticPublishPath: ./site
    pullRequestPreviewsEnabled: false
    headers:
      - path: "/*"
        name: X-Content-Type-Options
        value: nosniff
