services:
  - type: static_site
    name: metrooffice-website
    staticPublishPath: ./site
    buildCommand: ""
    pullRequestPreviewsEnabled: false
    headers:
      - path: "/*"
        name: X-Content-Type-Options
        value: nosniff
